<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXDxMVqo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXDxMVqo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXDxMVqo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXDxMVqo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXDxMVqo\App_KernelDevDebugContainer([
    'container.build_hash' => 'XDxMVqo',
    'container.build_id' => '00b45420',
    'container.build_time' => 1769683606,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXDxMVqo');
