<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB5r2fWw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB5r2fWw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB5r2fWw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB5r2fWw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB5r2fWw\App_KernelDevDebugContainer([
    'container.build_hash' => 'B5r2fWw',
    'container.build_id' => '3bcf3b2c',
    'container.build_time' => 1769686897,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB5r2fWw');
