<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_game_initialize' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::initialize'], [], [['text', '/api/game/initialize']], [], [], []],
    'api_game_color_order' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::getColorOrder'], [], [['text', '/api/game/color-order']], [], [], []],
    'api_game_color_order_new' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::generateNewColorOrder'], [], [['text', '/api/game/color-order/new']], [], [], []],
    'api_game_color_order_reorder' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::reorderColors'], [], [['text', '/api/game/color-order/reorder']], [], [], []],
    'api_game_color_order_confirm' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::confirmColorOrder'], [], [['text', '/api/game/color-order/confirm']], [], [], []],
    'api_game_values_order' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::getValuesOrder'], [], [['text', '/api/game/values-order']], [], [], []],
    'api_game_values_order_new' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::generateNewValuesOrder'], [], [['text', '/api/game/values-order/new']], [], [], []],
    'api_game_values_order_reorder' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::reorderValues'], [], [['text', '/api/game/values-order/reorder']], [], [], []],
    'api_game_values_order_confirm' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::confirmValuesOrder'], [], [['text', '/api/game/values-order/confirm']], [], [], []],
    'api_game_cards_number' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::confirmCardsNumber'], [], [['text', '/api/game/cards-number']], [], [], []],
    'api_game_unsorted_hand' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::getUnsortedHand'], [], [['text', '/api/game/unsorted-hand']], [], [], []],
    'api_game_sorted_hand' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::getSortedHand'], [], [['text', '/api/game/sorted-hand']], [], [], []],
    'api_game_reset' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::resetGame'], [], [['text', '/api/game/reset']], [], [], []],
    'App\Controller\Api\GameApiController::initialize' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::initialize'], [], [['text', '/api/game/initialize']], [], [], []],
    'App\Controller\Api\GameApiController::getColorOrder' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::getColorOrder'], [], [['text', '/api/game/color-order']], [], [], []],
    'App\Controller\Api\GameApiController::generateNewColorOrder' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::generateNewColorOrder'], [], [['text', '/api/game/color-order/new']], [], [], []],
    'App\Controller\Api\GameApiController::reorderColors' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::reorderColors'], [], [['text', '/api/game/color-order/reorder']], [], [], []],
    'App\Controller\Api\GameApiController::confirmColorOrder' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::confirmColorOrder'], [], [['text', '/api/game/color-order/confirm']], [], [], []],
    'App\Controller\Api\GameApiController::getValuesOrder' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::getValuesOrder'], [], [['text', '/api/game/values-order']], [], [], []],
    'App\Controller\Api\GameApiController::generateNewValuesOrder' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::generateNewValuesOrder'], [], [['text', '/api/game/values-order/new']], [], [], []],
    'App\Controller\Api\GameApiController::reorderValues' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::reorderValues'], [], [['text', '/api/game/values-order/reorder']], [], [], []],
    'App\Controller\Api\GameApiController::confirmValuesOrder' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::confirmValuesOrder'], [], [['text', '/api/game/values-order/confirm']], [], [], []],
    'App\Controller\Api\GameApiController::confirmCardsNumber' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::confirmCardsNumber'], [], [['text', '/api/game/cards-number']], [], [], []],
    'App\Controller\Api\GameApiController::getUnsortedHand' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::getUnsortedHand'], [], [['text', '/api/game/unsorted-hand']], [], [], []],
    'App\Controller\Api\GameApiController::getSortedHand' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::getSortedHand'], [], [['text', '/api/game/sorted-hand']], [], [], []],
    'App\Controller\Api\GameApiController::resetGame' => [[], ['_controller' => 'App\\Controller\\Api\\GameApiController::resetGame'], [], [['text', '/api/game/reset']], [], [], []],
];
